# ================================================================
# MyDreamTeam: separate-network ERGM (M0-M4)
#
# Inputs generated by 01_prepare_mdt_ergm_inputs.py:
#   data/processed/mydreamteam/mdt_nodes.csv
#   data/processed/mydreamteam/mdt_edges.csv
#   data/processed/mydreamteam/mdt_prior_mat.csv
#
# Outputs:
#   results/separate_networks/mydreamteam/mdt_ergm_results.xlsx
#   results/figures/mdt_collaboration_network.png
#
# The Python preprocessing script already applies log1p transformation and
# z-standardization. This script uses expertise_z and leadership_z directly.
# ================================================================


# ----------------------------------------------------------------
# 0. Command-line options
# ----------------------------------------------------------------

parse_options <- function(arguments) {
  defaults <- list(
    input_dir = file.path("data", "processed", "mydreamteam"),
    output_dir = file.path(
      "results", "separate_networks", "mydreamteam"
    ),
    figure_dir = file.path("results", "figures"),
    seed = 20260722L
  )

  if ("--help" %in% arguments || "-h" %in% arguments) {
    cat(
      paste(
        "Usage:",
        "  Rscript code/mydreamteam/02_run_mdt_ergm.R [options]",
        "",
        "Options:",
        "  --input-dir PATH   Directory containing the three processed CSV files",
        "  --output-dir PATH  Directory for mdt_ergm_results.xlsx",
        "  --figure-dir PATH  Directory for mdt_collaboration_network.png",
        "  --seed INTEGER     Random seed used for layout and model estimation",
        "  --help, -h         Show this help message",
        sep = "\n"
      ),
      "\n"
    )
    quit(save = "no", status = 0L)
  }

  allowed <- c(
    "--input-dir" = "input_dir",
    "--output-dir" = "output_dir",
    "--figure-dir" = "figure_dir",
    "--seed" = "seed"
  )

  options <- defaults
  position <- 1L

  while (position <= length(arguments)) {
    flag <- arguments[[position]]

    if (!flag %in% names(allowed)) {
      stop(sprintf("Unknown option: %s", flag), call. = FALSE)
    }
    if (position == length(arguments)) {
      stop(sprintf("Missing value after %s", flag), call. = FALSE)
    }

    value <- arguments[[position + 1L]]
    key <- unname(allowed[[flag]])

    if (key == "seed") {
      value <- suppressWarnings(as.integer(value))
      if (is.na(value)) {
        stop("--seed must be an integer.", call. = FALSE)
      }
    }

    options[[key]] <- value
    position <- position + 2L
  }

  options
}


options <- parse_options(commandArgs(trailingOnly = TRUE))

INPUT_DIR <- options$input_dir
OUTPUT_DIR <- options$output_dir
FIGURE_DIR <- options$figure_dir
SEED <- options$seed

NODES_FILE <- file.path(INPUT_DIR, "mdt_nodes.csv")
EDGES_FILE <- file.path(INPUT_DIR, "mdt_edges.csv")
PRIOR_FILE <- file.path(INPUT_DIR, "mdt_prior_mat.csv")

OUTPUT_FILE <- file.path(OUTPUT_DIR, "mdt_ergm_results.xlsx")
NETWORK_PLOT_FILE <- file.path(
  FIGURE_DIR,
  "mdt_collaboration_network.png"
)


# ----------------------------------------------------------------
# 1. Required packages
# ----------------------------------------------------------------

required_packages <- c("network", "ergm", "openxlsx", "igraph")
missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0L) {
  stop(
    paste0(
      "Missing required R package(s): ",
      paste(missing_packages, collapse = ", "),
      ".\nInstall them with:\ninstall.packages(c(",
      paste(sprintf('"%s"', missing_packages), collapse = ", "),
      "))"
    ),
    call. = FALSE
  )
}


# ----------------------------------------------------------------
# 2. Helper functions
# ----------------------------------------------------------------

assert_columns <- function(data, required, object_name) {
  missing <- setdiff(required, names(data))

  if (length(missing) > 0L) {
    stop(
      sprintf(
        "%s is missing required column(s): %s",
        object_name,
        paste(missing, collapse = ", ")
      ),
      call. = FALSE
    )
  }
}


read_prior_matrix <- function(path) {
  prior_raw <- read.csv(
    path,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    na.strings = c("", "NA", "NaN", "nan")
  )

  if (ncol(prior_raw) < 2L) {
    stop(
      "The prior-collaboration file does not contain a matrix.",
      call. = FALSE
    )
  }

  row_ids <- trimws(as.character(prior_raw[[1L]]))
  prior <- as.matrix(prior_raw[-1L])
  suppressWarnings(storage.mode(prior) <- "double")
  rownames(prior) <- row_ids
  colnames(prior) <- trimws(colnames(prior))

  if (nrow(prior) != ncol(prior)) {
    stop("The prior matrix is not square.", call. = FALSE)
  }
  if (anyDuplicated(rownames(prior)) > 0L ||
      anyDuplicated(colnames(prior)) > 0L) {
    stop(
      "The prior matrix contains duplicated row or column IDs.",
      call. = FALSE
    )
  }
  if (anyNA(prior) || any(!is.finite(prior))) {
    stop(
      "The prior matrix contains missing or non-finite values.",
      call. = FALSE
    )
  }
  if (!identical(rownames(prior), colnames(prior))) {
    stop(
      "The prior matrix row and column IDs are not in identical order.",
      call. = FALSE
    )
  }
  if (!isTRUE(all.equal(prior, t(prior), tolerance = 1e-12))) {
    stop("The prior matrix is not symmetric.", call. = FALSE)
  }
  if (any(!prior %in% c(0, 1))) {
    stop(
      "The prior matrix contains values other than 0 and 1.",
      call. = FALSE
    )
  }

  diag(prior) <- 0
  prior
}


pick_summary_column <- function(
  coefficient_table,
  candidates,
  default = NA_real_
) {
  matched <- candidates[candidates %in% names(coefficient_table)]

  if (length(matched) == 0L) {
    return(rep(default, nrow(coefficient_table)))
  }

  as.numeric(coefficient_table[[matched[[1L]]]])
}


extract_coefficients <- function(fit, dataset_name, model_name) {
  coefficient_table <- as.data.frame(summary(fit)$coefficients)

  data.frame(
    dataset = dataset_name,
    model = model_name,
    term = rownames(coefficient_table),
    Estimate = pick_summary_column(
      coefficient_table,
      "Estimate"
    ),
    Std_Error = pick_summary_column(
      coefficient_table,
      c("Std. Error", "Std.Error", "Std_Error")
    ),
    MCMC_percent = pick_summary_column(
      coefficient_table,
      c("MCMC %", "MCMC%", "MCMC_percent")
    ),
    z_value = pick_summary_column(
      coefficient_table,
      c("z value", "z.value", "z_value")
    ),
    p_value = pick_summary_column(
      coefficient_table,
      c("Pr(>|z|)", "p.value", "p_value")
    ),
    status = "ok",
    error = NA_character_,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}


empty_coefficient_table <- function() {
  data.frame(
    dataset = character(),
    model = character(),
    term = character(),
    Estimate = numeric(),
    Std_Error = numeric(),
    MCMC_percent = numeric(),
    z_value = numeric(),
    p_value = numeric(),
    status = character(),
    error = character(),
    stringsAsFactors = FALSE
  )
}


write_results_workbook <- function(sheet_data, output_path) {
  workbook <- openxlsx::createWorkbook()

  header_style <- openxlsx::createStyle(
    fontColour = "#FFFFFF",
    fgFill = "#1F4E78",
    textDecoration = "bold",
    halign = "center",
    valign = "center",
    border = "Bottom",
    borderColour = "#D9EAF7"
  )
  number_style <- openxlsx::createStyle(numFmt = "0.000000")
  scientific_style <- openxlsx::createStyle(numFmt = "0.000E+00")

  for (sheet_name in names(sheet_data)) {
    data <- sheet_data[[sheet_name]]

    openxlsx::addWorksheet(
      workbook,
      sheet_name,
      gridLines = FALSE
    )
    openxlsx::writeData(
      workbook,
      sheet = sheet_name,
      x = data,
      headerStyle = header_style,
      withFilter = nrow(data) > 0L
    )
    openxlsx::freezePane(
      workbook,
      sheet = sheet_name,
      firstRow = TRUE
    )
    openxlsx::setColWidths(
      workbook,
      sheet = sheet_name,
      cols = seq_len(max(1L, ncol(data))),
      widths = "auto"
    )

    if (nrow(data) == 0L) {
      next
    }

    numeric_columns <- which(vapply(data, is.numeric, logical(1)))
    p_columns <- which(names(data) == "p_value")
    ordinary_numeric <- setdiff(numeric_columns, p_columns)

    if (length(ordinary_numeric) > 0L) {
      openxlsx::addStyle(
        workbook,
        sheet = sheet_name,
        style = number_style,
        rows = 2:(nrow(data) + 1L),
        cols = ordinary_numeric,
        gridExpand = TRUE,
        stack = TRUE
      )
    }
    if (length(p_columns) > 0L) {
      openxlsx::addStyle(
        workbook,
        sheet = sheet_name,
        style = scientific_style,
        rows = 2:(nrow(data) + 1L),
        cols = p_columns,
        gridExpand = TRUE,
        stack = TRUE
      )
    }
  }

  dir.create(
    dirname(output_path),
    recursive = TRUE,
    showWarnings = FALSE
  )
  openxlsx::saveWorkbook(
    workbook,
    output_path,
    overwrite = TRUE
  )
}


# ----------------------------------------------------------------
# 3. Read and validate processed inputs
# ----------------------------------------------------------------

input_files <- c(NODES_FILE, EDGES_FILE, PRIOR_FILE)
missing_files <- input_files[!file.exists(input_files)]

if (length(missing_files) > 0L) {
  stop(
    paste0(
      "Missing input file(s):\n",
      paste(paste0("- ", missing_files), collapse = "\n"),
      "\nRun code/mydreamteam/01_prepare_mdt_ergm_inputs.py first."
    ),
    call. = FALSE
  )
}

nodes <- read.csv(
  NODES_FILE,
  stringsAsFactors = FALSE,
  check.names = FALSE,
  na.strings = c("", "NA", "NaN", "nan")
)
edges <- read.csv(
  EDGES_FILE,
  stringsAsFactors = FALSE,
  check.names = FALSE,
  na.strings = c("", "NA", "NaN", "nan")
)
prior_mat <- read_prior_matrix(PRIOR_FILE)

assert_columns(
  nodes,
  c(
    "global_id",
    "dataset",
    "user_id",
    "expertise_z",
    "leadership_z"
  ),
  "mdt_nodes.csv"
)
assert_columns(edges, c("u", "v"), "mdt_edges.csv")

nodes$global_id <- trimws(as.character(nodes$global_id))
nodes$user_id <- trimws(as.character(nodes$user_id))
nodes$dataset <- trimws(as.character(nodes$dataset))
nodes$expertise_z <- suppressWarnings(
  as.numeric(nodes$expertise_z)
)
nodes$leadership_z <- suppressWarnings(
  as.numeric(nodes$leadership_z)
)

edges$u <- trimws(as.character(edges$u))
edges$v <- trimws(as.character(edges$v))

if (nrow(nodes) < 2L) {
  stop(
    "The MDT node file contains fewer than two nodes.",
    call. = FALSE
  )
}
if (anyNA(nodes$global_id) || any(nodes$global_id == "")) {
  stop(
    "mdt_nodes.csv contains a missing global_id.",
    call. = FALSE
  )
}
if (anyDuplicated(nodes$global_id) > 0L) {
  stop(
    "mdt_nodes.csv contains duplicated global_id values.",
    call. = FALSE
  )
}
if (anyNA(nodes$expertise_z) ||
    any(!is.finite(nodes$expertise_z))) {
  stop(
    "expertise_z contains missing or non-finite values.",
    call. = FALSE
  )
}
if (anyNA(nodes$leadership_z) ||
    any(!is.finite(nodes$leadership_z))) {
  stop(
    "leadership_z contains missing or non-finite values.",
    call. = FALSE
  )
}
if (anyNA(edges$u) || anyNA(edges$v) ||
    any(edges$u == "") || any(edges$v == "")) {
  stop(
    "mdt_edges.csv contains a missing endpoint.",
    call. = FALSE
  )
}
if (any(edges$u == edges$v)) {
  stop(
    "mdt_edges.csv contains one or more self-ties.",
    call. = FALSE
  )
}

# Store every undirected edge in canonical endpoint order.
edges$u_original <- edges$u
edges$v_original <- edges$v
edges$u <- pmin(edges$u_original, edges$v_original)
edges$v <- pmax(edges$u_original, edges$v_original)
edges <- unique(edges[c("u", "v")])

node_ids <- nodes$global_id
unknown_edge_ids <- setdiff(
  unique(c(edges$u, edges$v)),
  node_ids
)

if (length(unknown_edge_ids) > 0L) {
  stop(
    sprintf(
      paste0(
        "The edge list contains endpoint IDs absent from ",
        "the node file: %s"
      ),
      paste(head(unknown_edge_ids, 10L), collapse = ", ")
    ),
    call. = FALSE
  )
}

if (!setequal(node_ids, rownames(prior_mat)) ||
    !setequal(node_ids, colnames(prior_mat))) {
  missing_in_prior <- setdiff(node_ids, rownames(prior_mat))
  extra_in_prior <- setdiff(rownames(prior_mat), node_ids)

  stop(
    paste0(
      "The node IDs and prior-matrix IDs do not match exactly.",
      "\nMissing from prior matrix: ",
      if (length(missing_in_prior) == 0L) {
        "none"
      } else {
        paste(head(missing_in_prior, 10L), collapse = ", ")
      },
      "\nExtra in prior matrix: ",
      if (length(extra_in_prior) == 0L) {
        "none"
      } else {
        paste(head(extra_in_prior, 10L), collapse = ", ")
      }
    ),
    call. = FALSE
  )
}

# Align the dyadic covariate to the exact network-vertex order.
prior_mat <- prior_mat[node_ids, node_ids, drop = FALSE]


# ----------------------------------------------------------------
# 4. Construct the observed undirected network
# ----------------------------------------------------------------

mdt_network <- network::network.initialize(
  n = nrow(nodes),
  directed = FALSE,
  loops = FALSE,
  multiple = FALSE
)

network::set.vertex.attribute(
  mdt_network,
  "vertex.names",
  node_ids
)
network::set.vertex.attribute(
  mdt_network,
  "expertise_z",
  nodes$expertise_z
)
network::set.vertex.attribute(
  mdt_network,
  "leadership_z",
  nodes$leadership_z
)

node_index <- setNames(seq_along(node_ids), node_ids)
tail_index <- unname(node_index[edges$u])
head_index <- unname(node_index[edges$v])

if (nrow(edges) > 0L) {
  network::add.edges(
    mdt_network,
    tail = tail_index,
    head = head_index
  )
}

if (network::network.edgecount(mdt_network) != nrow(edges)) {
  stop(
    "The constructed network edge count does not match the edge list.",
    call. = FALSE
  )
}

endpoint_frequency <- table(
  factor(c(edges$u, edges$v), levels = node_ids)
)
n_isolates <- sum(endpoint_frequency == 0L)

if (n_isolates > 0L) {
  warning(
    sprintf(
      paste0(
        "The analytical network contains %d isolate(s), although ",
        "preprocessing was expected to remove isolates."
      ),
      n_isolates
    ),
    call. = FALSE
  )
}

n_nodes <- nrow(nodes)
n_edges <- nrow(edges)
n_possible_dyads <- n_nodes * (n_nodes - 1) / 2
network_density <- if (
  n_possible_dyads > 0
) {
  n_edges / n_possible_dyads
} else {
  NA_real_
}
n_prior_pairs <- sum(prior_mat[upper.tri(prior_mat)] != 0)

message("\n===== MDT NETWORK SUMMARY =====")
message(sprintf("Number of nodes: %d", n_nodes))
message(sprintf("Number of edges: %d", n_edges))
message(sprintf("Number of isolates: %d", n_isolates))
message(sprintf("Network density: %.6f", network_density))
message(sprintf("Prior-collaboration pairs: %d", n_prior_pairs))


# ----------------------------------------------------------------
# 5. Plot the observed current-collaboration network
# ----------------------------------------------------------------

plot_nodes <- data.frame(
  name = node_ids,
  stringsAsFactors = FALSE
)
plot_edges <- data.frame(
  from = edges$u,
  to = edges$v,
  stringsAsFactors = FALSE
)
plot_graph <- igraph::graph_from_data_frame(
  d = plot_edges,
  directed = FALSE,
  vertices = plot_nodes
)

set.seed(SEED)
plot_layout <- igraph::layout_with_fr(
  plot_graph,
  niter = 1000,
  grid = "nogrid"
)

dir.create(
  dirname(NETWORK_PLOT_FILE),
  recursive = TRUE,
  showWarnings = FALSE
)
grDevices::png(
  filename = NETWORK_PLOT_FILE,
  width = 12,
  height = 12,
  units = "in",
  res = 300,
  bg = "white"
)
graphics::par(mar = c(0, 0, 2, 0))
plot(
  plot_graph,
  layout = plot_layout,
  vertex.size = 3.2,
  vertex.color = grDevices::adjustcolor(
    "#2F6DAE",
    alpha.f = 0.75
  ),
  vertex.frame.color = NA,
  vertex.label = NA,
  edge.color = grDevices::adjustcolor(
    "#6B7280",
    alpha.f = 0.15
  ),
  edge.width = 0.5,
  main = paste(
    "Observed MyDreamTeam Collaboration Network",
    "(Current Nodes and Edges)",
    sep = "\n"
  ),
  asp = 1,
  margin = 0.05
)
grDevices::dev.off()

message(
  sprintf(
    "[SAVED FIGURE] %s",
    normalizePath(NETWORK_PLOT_FILE, mustWork = FALSE)
  )
)


# ----------------------------------------------------------------
# 6. Define and estimate the nested M0-M4 sequence
# ----------------------------------------------------------------

model_formulas <- list(
  m0_edges = mdt_network ~ edges,
  m1_prior = mdt_network ~
    edges +
    edgecov(prior_mat),
  m2_prior_expertise = mdt_network ~
    edges +
    edgecov(prior_mat) +
    nodecov("expertise_z"),
  m3_prior_expertise_similarity = mdt_network ~
    edges +
    edgecov(prior_mat) +
    nodecov("expertise_z") +
    absdiff("expertise_z"),
  m4_full = mdt_network ~
    edges +
    edgecov(prior_mat) +
    nodecov("expertise_z") +
    absdiff("expertise_z") +
    nodecov("leadership_z") +
    absdiff("leadership_z")
)

set.seed(SEED)

fitted_models <- list()
model_fit_rows <- list()
failed_rows <- list()

for (model_name in names(model_formulas)) {
  message(sprintf("[RUNNING] %s", model_name))

  fit_attempt <- tryCatch(
    ergm::ergm(model_formulas[[model_name]]),
    error = function(error) error
  )

  if (inherits(fit_attempt, "error")) {
    error_text <- conditionMessage(fit_attempt)
    message(sprintf("[FAILED] %s: %s", model_name, error_text))

    model_fit_rows[[model_name]] <- data.frame(
      dataset = "MyDreamTeam",
      model = model_name,
      AIC = NA_real_,
      BIC = NA_real_,
      status = "failed",
      error = error_text,
      stringsAsFactors = FALSE
    )
    failed_rows[[model_name]] <- model_fit_rows[[model_name]]
  } else {
    fitted_models[[model_name]] <- fit_attempt
    model_fit_rows[[model_name]] <- data.frame(
      dataset = "MyDreamTeam",
      model = model_name,
      AIC = as.numeric(stats::AIC(fit_attempt)),
      BIC = as.numeric(stats::BIC(fit_attempt)),
      status = "ok",
      error = NA_character_,
      stringsAsFactors = FALSE
    )

    message(sprintf("[OK] %s", model_name))
  }
}

model_fit <- do.call(rbind, model_fit_rows)
rownames(model_fit) <- NULL

failed_models <- if (length(failed_rows) > 0L) {
  failed_output <- do.call(rbind, failed_rows)
  rownames(failed_output) <- NULL
  failed_output
} else {
  data.frame(
    dataset = character(),
    model = character(),
    AIC = numeric(),
    BIC = numeric(),
    status = character(),
    error = character(),
    stringsAsFactors = FALSE
  )
}

# Match the other separate-network result workbooks:
# coefficients contains M4; model_fit contains M0-M4.
coefficients <- if ("m4_full" %in% names(fitted_models)) {
  extract_coefficients(
    fitted_models[["m4_full"]],
    dataset_name = "MyDreamTeam",
    model_name = "m4_full"
  )
} else {
  empty_coefficient_table()
}


# ----------------------------------------------------------------
# 7. Record summaries and reproducibility information
# ----------------------------------------------------------------

network_summary <- data.frame(
  dataset = "MyDreamTeam",
  nodes = n_nodes,
  edges = n_edges,
  possible_dyads = n_possible_dyads,
  density = network_density,
  isolates = n_isolates,
  prior_nonzero = n_prior_pairs,
  nodes_file = basename(NODES_FILE),
  edges_file = basename(EDGES_FILE),
  prior_file = basename(PRIOR_FILE),
  network_figure = basename(NETWORK_PLOT_FILE),
  stringsAsFactors = FALSE
)

run_settings <- data.frame(
  setting = c(
    "analysis",
    "model_sequence",
    "outcome_network",
    "prior_collaboration",
    "expertise_variable",
    "leadership_variable",
    "attribute_preprocessing",
    "coefficient_sheet_scope",
    "random_seed",
    "R_version",
    "network_version",
    "ergm_version",
    "openxlsx_version",
    "igraph_version"
  ),
  value = c(
    "Separate-network ERGM for MyDreamTeam",
    paste0(
      "M0 edges; M1 + prior; M2 + expertise level; ",
      "M3 + expertise difference; ",
      "M4 + leadership level and difference"
    ),
    "Undirected and binary",
    "Binary edge covariate",
    "expertise_z",
    "leadership_z",
    paste0(
      "Computed in Python preprocessing; ",
      "no second transformation in R"
    ),
    paste0(
      "Complete model M4 only; ",
      "M0-M4 fit statistics are in model_fit"
    ),
    as.character(SEED),
    R.version.string,
    as.character(utils::packageVersion("network")),
    as.character(utils::packageVersion("ergm")),
    as.character(utils::packageVersion("openxlsx")),
    as.character(utils::packageVersion("igraph"))
  ),
  stringsAsFactors = FALSE
)


# ----------------------------------------------------------------
# 8. Write the result workbook
# ----------------------------------------------------------------

sheet_data <- list(
  coefficients = coefficients,
  model_fit = model_fit,
  network_summary = network_summary,
  failed_models = failed_models,
  run_settings = run_settings
)

write_results_workbook(sheet_data, OUTPUT_FILE)

message("\n===== MDT ERGM COMPLETE =====")
message(sprintf("Successful models: %d/5", length(fitted_models)))
message(
  sprintf(
    "[SAVED RESULTS] %s",
    normalizePath(OUTPUT_FILE, mustWork = FALSE)
  )
)
